version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: finops-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finops_portal
    ports:
      - "54332:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: finops_postgres_data
